### ISSUE TITLE
Media selector closes prematurely when in popover

### ISSUE THREAD

**Issue by coreyward** [robinpyon/sanity-plugin-media#1]
When using a structure like the following where there is an image field on an object that is in an array, and the array is configured to show in a popover, attempting to select an image from Media fails. The Media window pulls up as expected, but attempting to select an image results in the Media window closing immediately without an error or selection.

```js
{
  // …
  fields: [
    {
      title: "Actions",
      name: "actions",
      type: "array",
      of: [
        {
          type: "object",
          fields: [{ name: "image", type: "image" }],
        },
      ],
    },
  ],
  options: {
    editModal: "popover",
  },
}
```

Removing the `editModal` property from `options` on the object resolves the issue.

**Comment by robinpyon** [comment]
Thanks for reporting this @coreyward, that should be resolved now – and sorry about the delay here. (Better late than never!)
