### ISSUE TITLE
React Icons 3 bloats bundle size

### ISSUE THREAD

**Issue by piersolenski** [robinpyon/sanity-plugin-media#11]
React Icons 3 currently includes all icons from all sets when bundled https://github.com/react-icons/react-icons/issues/154 - resulting in huge bundle sizes of up to **8mb**.

It might be worth downgrading to `2.2.7` until `react-icons` fix the issue or Sanity can update their webpack configuration. https://github.com/sanity-io/sanity/issues/1537#issuecomment-660391631.

**Comment by robinpyon** [comment]
`react-icons` is no longer used as a dependency in 1.0, and this plugin now uses Sanity-provided icons in `@sanity/icons`!
