### ISSUE TITLE
Display other asset types

### ISSUE THREAD

**Issue by ciampo** [robinpyon/sanity-plugin-media#2]
It would be great if the media gallery plugin also displayed other assets (`sanity.fileAsset`), at least videos.

(Happy to help to implement this feature with some guidance!)

**Comment by robinpyon** [comment]
I'm not yet sure this is (currently) possible!

For this to work, I believe Sanity would need to not only add support for [custom asset sources](https://www.sanity.io/docs/custom-asset-sources) on file input fields (AFAIK it's only supported on image field inputs), but it'd also need to provide additional contextual information to any asset source plugin on what type of field opened it 

e.g. If a user opened the plugin from an image field, we'd want to then filter out all non-image assets. Similarly, if the plugin was opened from the navbar then we'd want to show everything

**Comment by ciampo** [comment]
Thank you @robinpyon for the answer! 

I see. Would be great to get an "official" Sanity response on it — do you think you can enquire?

**Comment by robinpyon** [comment]
This plugin now displays documents of type `sanity.fileAsset` when browsing assets in 1.0! (e.g. when opening the plugin via the navbar)

However, it's still not yet possible to use it as a custom asset source for non-images, but hopefully it's something Sanity will expose soon

**Comment by hdoro** [comment]
@robinpyon congrats on 1.0 🎉  On custom assets, do you know if it'd possible to add non-native assets to the media browser? The use case I'm thinking about is specifically showing and tagging mux/vimeo videos, but I can think of this feature being useful for other things, such as images from external services (Cloudinary, Firebase, etc.).

We can have other asset sources for that, of course, so if this isn't in scope I'm 100% in support of it. But I figured having a single library could be beneficial to many as it'd streamline tagging and UX :)

PS: figured this is a better place for this question than an issue, let me know if I should create a new issue instead.

**Comment by robinpyon** [comment]
> On custom assets, do you know if it'd possible to add non-native assets to the media browser? 

This is a great idea and one that would be possible in theory, though the plugin would need to expose user config to be able to specify:
- which document types are queried
- how their previews are generated (e.g. with a mux video, you'd want that to presumably point to the generated thumbnail) 
- what metadata is exposed (e.g. displaying video encoding details, video duration bitrate and whatever else is exposed)
- post-delete actions (e.g. you may want to delete the video at mux in addition to the linked sanity entry)
- additionally – once upload support is added – the plugin would need to know how to manage uploads to custom sources (or just not support it at all, which would work against the idea of having it display assets across other external services)

Not to say it's not in scope, though there's a whole laundry list of other items which would need to come first - support for uploads being the main one!
