### ISSUE TITLE
can't select image through plugin (sanity 2.3.8)

### ISSUE THREAD

**Issue by ovsw** [robinpyon/sanity-plugin-media#24]
With Sanity 2.3.8 it's not possible to select an image through the plugin. When hitting the "select" button, the plugin page opens up but clicking on an image just opens up the image properties (just like if I were to click on it from the plugin's page).

I have another install with sanity 2.3.3 which works just fine. Both sanity instances use `"sanity-plugin-media": "^1.0.1"`

**Comment by robinpyon** [comment]
Hey @ovsw, there was a [minor regression](https://github.com/sanity-io/sanity/issues/2316) in Sanity `2.3.8` where custom asset sources were no longer being passed the current `document` prop – which in turn, meant that the plugin couldn't properly determine whether it's in a selection or browsing context

I pushed a quick fix for this in `1.0.2`, please give that a go and let me know if that works for you!

**Comment by ovsw** [comment]
Thanks @robinpyon, that fixed it!
