### ISSUE TITLE
Is the "Current Entry" option coming back?

### ISSUE THREAD

**Issue by good-idea** [robinpyon/sanity-plugin-media#26]
The ability to select from images that are only associated with the current document is really helpful - especially for one of my clients with a massive dataset with thousands of images. Will this be re-implemented in `1.x`?

For now, I've reverted to `0.4.0` because this feature is crucial for them.

**Comment by good-idea** [comment]
And, I'd be happy to make a PR that does this! I'm thinking it would be more performant to traverse the `document` and extract all image refs instead of making another query?

**Comment by robinpyon** [comment]
Hey @good-idea – in all honesty, this is something that just got accidentally left behind when switching to search facets! 

> I'm thinking it would be more performant to traverse the document and extract all image refs instead of making another query?

That makes way more sense then what `0.4.0` currently does, which is the following GROQ query (which must be quite slow on your client's dataset with 1000s of images). Curious to know how long that lookup takes

```
*[
  _type == "sanity.imageAsset" && 
  defined(*[_id == $documentId && references(^._id)][0])
]
```

There's no getting around another query though, but recursively grabbing those image asset refs (from the provided `document`) and fetching those assets individually should be _much_ faster. I'll definitely look to add this shortly!

**Comment by good-idea** [comment]
Fantastic, thank you!

**Comment by robinpyon** [comment]
In `1.1.2`, an **"In use in current document"** search facet is now accessible when selecting images within an existing document

It should be much faster now, as it's just recursively pulling those refs from the current document as suggested (rather than querying every single image, which was pretty mad in hindsight)

Let me know if that doesn't work out for you!

**Comment by fabien** [comment]
@robinpyon I'm working with an `image` derived `productImage` type (with custom fields) in an array. Is this the reason why such images are not being picked up by the **In use in current document** option? I presume this currently queries for `image` types only?
