### ISSUE TITLE
Plugin contaminating studio form input styles

### ISSUE THREAD

**Issue by robinpyon** [robinpyon/sanity-plugin-media#31]
![image](https://user-images.githubusercontent.com/209129/111906654-6d8af100-8a49-11eb-8bb4-dfc9978a0e10.png)

There have been [reports](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1616180671132100) of the plugin altering styles of other form fields _outside the plugin_ – from what I can gather, this seems to happen once the media plugin has been opened at least once.

I'd wager that it's possibly linked to a dependency issue with `styled-components` and/or `@sanity/ui`, [which has since been patched out](https://github.com/sanity-io/sanity/issues/2190)

For those who are experiencing this issue:
- Have you tried clearing your `node_modules` and re-installing all modules? (This has fixed various dependency issues with `@sanity/ui` in the past)
- What version of the plugin are you running?
- Please paste your output of `sanity versions`
- Does this happen across both dev + deployed environments?
- Is opening the plugin enough to trigger this issue? (E.g. does it occur if you open it as a tool and immediately close it?)

**Comment by evenwestvang** [comment]
Thanks for following up @robinpyon - I'll suggest support redirect queries here

**Comment by dane-brown** [comment]
**Have you tried clearing your node_modules and re-installing all modules? (This has fixed various dependency issues with @sanity/ui in the past)**
Only having the issue on deployed env.

**What version of the plugin are you running?**
1.0.2

**Please paste your output of sanity versions**
    "@sanity/base": "^2.7.1",
    "@sanity/color-input": "^2.2.6",
    "@sanity/components": "^2.2.6",
    "@sanity/core": "^2.7.1",
    "@sanity/dashboard": "^2.7.0",
    "@sanity/default-layout": "^2.7.1",
    "@sanity/default-login": "^2.7.0",
    "@sanity/desk-tool": "^2.7.1",

**Does this happen across both dev + deployed environments?**
Only happens  on deployed env for me.

**Is opening the plugin enough to trigger this issue? (E.g. does it occur if you open it as a tool and immediately close it?)**
Yes choosing Select -> Media once  is enough to cause the issue.

**Comment by robinpyon** [comment]
Thanks @dane-brown - does the issue still persist in the latest version of the media plugin? (`1.2.0` as of writing)

**Comment by dane-brown** [comment]
@robinpyon Problem persists even on `v1.2.0`

**Comment by robinpyon** [comment]
@dane-brown Can you please try removing all your existing node modules, re-install deps and re-deploy with:
`rm -rf node_modules && yarn && sanity deploy`

And if that doesn't work, please paste a dump of your `package.json` and `yarn why styled-components` and hopefully I can look to replicate

**Comment by jorngeorg** [comment]
Hi @robinpyon, I think this issue is resolved with the latest release of @sanity/ui (https://github.com/sanity-io/design/commit/3c6cc683d17431e7ca8bd43908a0e16854af574a). 

Can you try that and report back? :bow:

**Comment by robinpyon** [comment]
Thanks @jorngeorg! I've bumped @sanity/ui to `0.33.11` in `1.2.1` 

Unfortunately I've been unable to replicate the issue (even prior to the update) but hopefully this resolves it! Be great if you could validate @dane-brown

... think I just need to bite the bullet and move `@sanity/ui` to peer deps as a breaking change

**Comment by dane-brown** [comment]
@robinpyon I host the studio on vercel which does a fresh install every deployment.

As requested please see `package.json` and `yarn why styled-components`


```
{
  "private": true,
  "version": "1.0.0",
  "description": "",
  "main": "package.json",
  "scripts": {
    "start": "sanity start",
    "test": "sanity check",
    "build": "sanity build public -y",
  },
  "keywords": [
    "sanity"
  ],
  "dependencies": {
    "@sanity/base": "^2.7.1",
    "@sanity/color-input": "^2.2.6",
    "@sanity/components": "^2.2.6",
    "@sanity/core": "^2.7.1",
    "@sanity/dashboard": "^2.7.0",
    "@sanity/default-layout": "^2.7.1",
    "@sanity/default-login": "^2.7.0",
    "@sanity/desk-tool": "^2.7.1",
    "@sanity/vision": "^2.7.0",
    "apexcharts": "^3.8.6",
    "chart.js": "^2.8.0",
    "get-it": "^4.1.4",
    "get-youtube-id": "^1.0.1",
    "prop-types": "^15.6",
    "react": "^16.2",
    "react-chartkick": "^0.3.2",
    "react-dom": "^16.2",
    "react-google-charts": "^3.0.15",
    "react-icons": "^3.7.0",
    "sanity-plugin-asset-source-giphy": "^0.0.12",
    "sanity-plugin-asset-source-unsplash": "^0.1.1",
    "sanity-plugin-content-model-graph": "^1.1.0",
    "sanity-plugin-dashboard-widget-cats": "^0.0.2",
    "sanity-plugin-dashboard-widget-document-list": "^0.0.11",
    "sanity-plugin-datatable": "^1.0.5",
    "sanity-plugin-media": "^1.2.0",
    "sanity-plugin-table": "^1.0.1"
  },
  "devDependencies": {
    "@sanity/cli": "^2.7.1"
  }
}
```


```
yarn why v1.19.1
[1/4] 🤔  Why do we have the module "styled-components"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "styled-components@5.2.1"
info Has been hoisted to "styled-components"
info Reasons this module exists
   - Hoisted from "@sanity#base#styled-components"
   - Hoisted from "@sanity#default-layout#styled-components"
   - Hoisted from "@sanity#desk-tool#styled-components"
   - Hoisted from "sanity-plugin-media#styled-components"
   - Hoisted from "@sanity#desk-tool#@sanity#field#styled-components"
   - Hoisted from "@sanity#desk-tool#@sanity#form-builder#styled-components"
   - Hoisted from "@sanity#desk-tool#@sanity#form-builder#@sanity#portable-text-editor#styled-components"
info Disk size without dependencies: "1.46MB"
info Disk size with unique dependencies: "2.59MB"
info Disk size with transitive dependencies: "13.06MB"
info Number of shared dependencies: 38
=> Found "sanity-plugin-content-model-graph#styled-components@5.1.0"
info This module exists because "sanity-plugin-content-model-graph" depends on it.
info Disk size without dependencies: "1.46MB"
info Disk size with unique dependencies: "2.59MB"
info Disk size with transitive dependencies: "13.07MB"
info Number of shared dependencies: 38
=> Found "sanity-plugin-datatable#styled-components@3.4.10"
info This module exists because "sanity-plugin-datatable" depends on it.
info Disk size without dependencies: "4.62MB"
info Disk size with unique dependencies: "6.42MB"
info Disk size with transitive dependencies: "7.56MB"
info Number of shared dependencies: 22
=> Found "sanity-plugin-asset-source-giphy#styled-components@4.4.1"
info This module exists because "sanity-plugin-asset-source-giphy" depends on it.
info Disk size without dependencies: "1.64MB"
info Disk size with unique dependencies: "3MB"
info Disk size with transitive dependencies: "13.6MB"
info Number of shared dependencies: 42
✨  Done in 1.05s.
```

**Comment by robinpyon** [comment]
Just confirmed with @dane-brown that `1.2.2` solves the issue – thanks again for following up here @jorngeorg!
