### ISSUE TITLE
Media plugin breaking Sanity studio with "can't access property "sanity", theme is undefined"

### ISSUE THREAD

**Issue by lanelps** [robinpyon/sanity-plugin-media#41]
<img width="408" alt="Screen Shot 2021-05-28 at 5 13 51 PM" src="https://user-images.githubusercontent.com/28562945/120058207-66add980-c09d-11eb-9c97-ff19503bdfb8.png">

Using with latest available Sanity 2.10.5, but seems to break with previous versions as well.

**Comment by arlenpeiffer** [comment]
same issue here 🙋‍♂️

**Comment by robinpyon** [comment]
Thanks for flagging this!

Unfortunately this does seem to be an ongoing issue and I don't believe it's linked to this plugin specifically, nor is it something I can easily recreate.

The general advice from Sanity in a case like this is to delete your `node_modules` folder and re-install your dependencies with `npm install` or equivalent. Can you please try that and let me know if that resolves the issue for you?

Some more context: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1619809558425100

**Comment by AndrewGodwin86** [comment]
I was getting a very similar error: `theme is undefined`. Deleting the node_modules folder and running npm install fixed the issue for me.

**Comment by lanelps** [comment]
Unfortunately removing the `node_modules` folder and running `yarn` didn’t work for me. 

The only resolve I found was to start a fresh sanity project and install dependencies one by one until the error showed. 

In my case adding the media plugin caused the error as soon as it was installed. I’m still not entirely sure why though.

**Comment by jacobgranberry** [comment]
Tried all solutions in this issue, no dice.  Getting the same error.

**Comment by 3200pro** [comment]
Still an issue. Here's some more information regarding it:

https://github.com/sanity-io/sanity/issues/2190#issuecomment-794207036

**Comment by joshuaellis** [comment]
I just ran into this issue, but updating my sanity deps to `2.11.0` resolved these issues, maybe Sanity have fixed the issue?

**Comment by robinpyon** [comment]
@joshuaellis Did you happen to run `sanity upgrade` prior to the issue occuring, or was this after a 'fresh' install?

It seems like `2.11.0` has resolved issues [with sanity upgrade with incorrect `node_modules`](https://github.com/sanity-io/sanity/releases/tag/v2.11.0) though I'm not 100% sure if this a panacea, as it seems like people were previously encountering this when manually installing too.

---

For those still encountering the issue, please try: 
- upgrading sanity to `2.11.0` 
- and / or if that fails,  install `sanity-media-plugin: 2.0.0-alpha.1` (which removes an old version of `@sanity/base` as peer dependency and has bumped `@sanity/ui` too) 🤞

**Comment by 3200pro** [comment]
Looks like something got updated with the most recent version of Sanity (2.11.0) Working well here.

**Comment by lanelps** [comment]
Upgrading to the latest sanity `2.11.0` with `sanity upgrade` solved all issues for me!

**Comment by robinpyon** [comment]
Awesome! 

For reference, the issue appeared to be the version of yarn Sanity CLI was packaged with, [which was updated in 2.11.0](https://github.com/sanity-io/sanity/commit/47186e20643fb2138a715e7f1c6110b1b66069b4)
