### ISSUE TITLE
Slow query at scale

### ISSUE THREAD

**Issue by dvmonroe** [robinpyon/sanity-plugin-media#46]
First off, thanks a ton @robinpyon for the plugin. Saves us a lot of work!

In the process of migrating over our assets and tag to Sanity (7k assets and 2400 tags) our users' browsers were consistently crashing when accessing the media library. With some digging on the the network tab it looks like this query here is the main issue:

https://github.com/robinpyon/sanity-plugin-media/blob/cfa18eaf3b63828d63df8c5fb962e5877df57a5b/src/modules/tags/index.ts#L155

Pulling back 2400 tags from sanity via GROQ multiple times on page appears to be the crashing point.

I'm wondering if there's a better way here to display the tags to the end user while limiting the amount of tags we're pulling in a single query.

If our team can be of help at all in thinking about a solution don't hesitate to reach out.

**Comment by robinpyon** [comment]
Thanks for flagging this @dvmonroe, really glad you've found the plugin helpful!

I can honestly say I never anticipated that many tags being used! But it certainly highlights a serious flaw, and is something I'll be able to look into shortly.

More specifically..
- Not fetching all tags at once and instead lazy-load in batches (similar to how assets are brought in)
- Virtualising that tag display (I'd wager this is the main culprit for poor performance)
- Using the latest version of GROQ (as the plugin is still using v1) which should speed things up too

**Comment by robinpyon** [comment]
That fix is now live in `1.4.0`!
