### ISSUE TITLE
Silent Upload Failure if `window.crypto.subtle` Not Available

### ISSUE THREAD

**Issue by mutewinter** [robinpyon/sanity-plugin-media#50]
Heads-up that I got caught by this `TODO`: https://github.com/robinpyon/sanity-plugin-media/blob/master/src/modules/uploads/index.ts#L198

Turns out if you use a custom domain locally like `http://my-site.test:3000`, `window.crypto.subtle` isn't defined in that environment. Instead, you have to use `localhost:3000` when using this plugin. It would be nice if there were a Toasted error message if the file hash generation fails. Or perhaps even disable upload entirely if the crypto APIs aren't available.

**Comment by robinpyon** [comment]
Great catch, thank you for flagging this @mutewinter. 

A toast will now be displayed when trying to generate hashes / upload files from within insecure contexts in `1.4.11`
