### ISSUE TITLE
Cannot retrieve altText and other data when image is in Block Content (Richt Text)

### ISSUE THREAD

**Issue by ratkorle** [robinpyon/sanity-plugin-media#55]
Hi,
I am using this plug in. For Images that are as document field this works great. But when Image is in Block Content I only get:
```
"image": {
                    "_type": "image",
                    "asset": {
                      "_ref": "image-xxxx-1544x726-jpg",
                      "_type": "reference"
                    }
```

This is my query (where challenge is a Rich Text field):
```
allSanityCaseStudies {
    edges {
      node {
        challenge {
          _raw
        }
      }
    }
  }
```

I am expecting `image.asset` to have all descriptive fields.

Does this require additional action?

**Comment by robinpyon** [comment]
Hey @ratkorle, I believe this is more a GraphQL issue (which I don't really use on a daily basis, but having a stab here)

By default, Sanity's GraphQL schema generator [won't resolve references in Portable text](https://www.sanity.io/docs/graphql#5ea9c0e79586) – but if you are using a resolver (like `gatsby-source-sanity`), they [provide arguments](https://github.com/sanity-io/gatsby-source-sanity#raw-fields) you can use to resolve image references and drill down into those assets.

I should stress that whilst you will be able to query `altText`, `description` and `title` fields on image assets, you won't be able to query media tags:
> Currently, `opt.media.tags` on assets aren't accessible via GraphQL. This is because `opt` is a custom object used by this plugin and not part of Sanity's asset schema.

Hope that helps!
