### ISSUE TITLE
last item in menuFacets is not rendered

### ISSUE THREAD

**Issue by SvSven** [robinpyon/sanity-plugin-media#57]
While working on https://github.com/robinpyon/sanity-plugin-media/pull/56, I noticed that the last item in the list of filters (in this case `height`) is not being rendered.

Doesn't seem to be specific to the config of the height filter, because adding an additional item to the end of the list will then render the height filter but not the newly added last item.

**Comment by robinpyon** [comment]
Thanks @SvSven! That's now fixed in `1.4.11`
