### ISSUE TITLE
Custom asset source

### ISSUE THREAD

**Issue by MartCube** [robinpyon/sanity-plugin-media#65]
Hello there :v: 
First wanna say thanks for this great plugin !
I want to ask is there a way when you click 'browse' to upload image to open 'Media Plugin' as default.
Currently on click I have a drop-down of 'uploaded images' and 'media'.

**Comment by robinpyon** [comment]
Hey @MartCube – this is possible! 

You'll need to do a bit of extra work and enable it as a [custom asset source](https://github.com/robinpyon/sanity-plugin-media#enabling-it-as-a-global-custom-asset-source) – if you follow those instructions, you can then bypass Sanity's default file picker and open the media plugin by default when selecting assets.
