### ISSUE TITLE
Blurhash not working with plugin

### ISSUE THREAD

**Issue by EilifAkerjordet** [robinpyon/sanity-plugin-media#68]
I can't get blurhash to work, and i suspect i might me because of this line here? 

https://github.com/robinpyon/sanity-plugin-media/blob/e71ae9f192c7c3e4b8b2a31d8d5239b5c75be78b/src/utils/uploadSanityAsset.ts#L83

**Comment by robinpyon** [comment]
Thanks @EilifAkerjordet. 

Blurhash is correctly extracted in the latest version of this plugin – though note that this will only apply to new uploads!
