### ISSUE TITLE
plugin broken on mobile

### ISSUE THREAD

**Issue by moa-os** [robinpyon/sanity-plugin-media#70]
<img width="391" alt="Screenshot 2022-03-07 at 15 31 15" src="https://user-images.githubusercontent.com/14351287/157053596-97f1277e-b21a-4a93-aaa9-42a0baf52f58.png">

The plugin is working perfectly on PC/mac, but not working on mobile. Any soultion? our editor uses mobile as their primary editing tool

**Comment by robinpyon** [comment]
Hey @moa-os, thanks for flagging this. 

The plugin should now render correctly at smaller breakpoints as expected!
