### ISSUE TITLE
Can't select the image from the media browser

### ISSUE THREAD

**Issue by kizeesmack** [robinpyon/sanity-plugin-media#78]
An Error is returned 

**Error: Returned value must be an array with at least one item (asset)**

using  "@sanity/base": "^2.29.5",

**Comment by robinpyon** [comment]
Oof. That regression's fixed in `1.4.8` – thanks for flagging this @kizeesmack!

**Comment by kizeesmack** [comment]
Thank you @robinpyon  is there any workaround for me to use this in the meanwhile?

**Comment by robinpyon** [comment]
If you update your plugin to use `1.4.8` you should be good to go – please let me know if you're still having issues.

**Comment by kizeesmack** [comment]
oh I just saw the release! thank you
