### ISSUE TITLE
In select asset view, no filters can be added.

### ISSUE THREAD

**Issue by roffelsaurus** [robinpyon/sanity-plugin-media#82]
When in select asset mode, the button "Add filter" does nothing. No errors either.

When opening the plugin using top bar "Media", so in general browsing mode, the button works with no issues.

sanity-plugin-media 1.4.4 (also tested 1.4.9, no difference).
sanity-X 2.30.1

If this does not reproduce for you, I'm happy to supply addition info, but hard to know what is pertinent.

**Comment by robinpyon** [comment]
Thanks @roffelsaurus – this is an interesting one. I'm unable to repro on `1.4.10` with sanity `2.30.1`.

Are you able to try nuke your `node_modules`, reinstall dependencies and see if that works for you? 

Otherwise, the output of your `package.json` and `yarn why @sanity/ui` may also be useful.

**Comment by rylanharper** [comment]
I am not sure if this is related, but I had major breaking issues with this plugin using `1.4.10` and `react` + `react-dom` version `^18.0.0` (I think the latest version is `18.0.1`) --- Downgrading to v `17.0.0` fixed everything:)

**Comment by roffelsaurus** [comment]
I attempted a clean reinstallation of node_modules, but that did not work.

You mentioned @sanity/ui and noticed that I had the legacy version of that @sanity/components. I dropped that completely and instead rewrote to use latest @sanity/ui on a couple of custom inputs, then did another clean reinstallation, but unfortunately that did not work either.

package.json deps:

```
"dependencies": {
    "@sanity/base": "^2.30.1",
    "@sanity/cli": "^2.30.0",
    "@sanity/core": "^2.30.1",
    "@sanity/default-layout": "^2.30.1",
    "@sanity/default-login": "^2.30.1",
    "@sanity/desk-tool": "^2.30.1",
    "@sanity/ui": "^0.37.11",
    "@sanity/vision": "^2.30.1",
    "axios": "^0.27.2",
    "base32-encode": "^1.2.0",
    "dotenv": "^10.0.0",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-icons": "^4.4.0",
    "sanity-plugin-media": "^1.4.10",
    "styled-components": "^5.3.5"
  }
```

```
yarn why @sanity/ui
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "@sanity/ui"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@sanity/ui@0.37.11"
info Has been hoisted to "@sanity/ui"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "sanity-plugin-media#@sanity#ui"
   - Hoisted from "@sanity#base#@sanity#ui"
   - Hoisted from "@sanity#default-layout#@sanity#ui"
   - Hoisted from "@sanity#default-login#@sanity#ui"
   - Hoisted from "@sanity#desk-tool#@sanity#ui"
   - Hoisted from "@sanity#vision#@sanity#ui"
   - Hoisted from "@sanity#desk-tool#@sanity#field#@sanity#ui"
   - Hoisted from "@sanity#desk-tool#@sanity#form-builder#@sanity#ui"
info Disk size without dependencies: "9.48MB"
info Disk size with unique dependencies: "20.38MB"
info Disk size with transitive dependencies: "27.83MB"
info Number of shared dependencies: 23
✨  Done in 0.95s.
```

**Comment by robinpyon** [comment]
Apologies on the latency here, @roffelsaurus 

This should be fixed in `1.4.11` – z-indices are no longer hardcoded and depth is now managed with Sanity UI. Please do shout if you're still seeing issues here.

**Comment by schrockwell** [comment]
@arjanmalda I am also experiencing this same issue. 

When using the Media picker from the top bar, the "Add filter" menu popover is inserted into a portal element `div[data-portal]` at the bottom of the page, which works.

<img width="519" alt="image" src="https://github.com/sanity-io/sanity-plugin-media/assets/30214/e3367876-4cf1-44ad-8489-fe757a9468f2">

When clicking "Add filter" from a form field, the popover menu is instead added to a `div.media-portal` element, but it has the `hidden` attribute applied, which prevents it from showing. 

<img width="519" alt="image" src="https://github.com/sanity-io/sanity-plugin-media/assets/30214/b3d039e0-2b04-471e-b060-2716904201af">

I'm not sure why there is a difference between these two approaches yet.

**Comment by arjanmalda** [comment]
@schrockwell Thank you for opening the other issue 👍
