### ISSUE TITLE
Select button is invisible on light background images

### ISSUE THREAD

**Issue by jdwillemse** [robinpyon/sanity-plugin-media#9]
When the image is white or of a light colour the select button is not visible. I propose we give it a background colour and for extra clarity add a text label.

This is what the problem looks like
![Screenshot 2020-07-14 at 12 46 11](https://user-images.githubusercontent.com/1798297/87417295-37e75b80-c5d0-11ea-87b3-2125c07e5dab.png)

Suggestion for solving the issue
![Screenshot 2020-07-14 at 14 33 34](https://user-images.githubusercontent.com/1798297/87426118-0d50cf00-c5df-11ea-91df-c2c1c8d87871.png)

I can make a PR for this if my suggestion is acceptable.

**Comment by Grsmto** [comment]
Cool stuff for the background! 
However I'm not sure the label text is needed, if the icon is clear enough (and I think it is). 
For example Google Photos has this functionality but no label:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/527559/87740537-d1716180-c7b8-11ea-8849-4e0e87d46269.png">

**Comment by jdwillemse** [comment]
With Google the entire frame is the hit area, not just the small checkmark. 

The function of the checkmark is also different. With Google, it is a state indication whereas in the media lib it is a call to action. There is also no instruction text to guide the user as there is with Google. 

The label is better for accessibility and users new to the interface. I myself missed this button when I first started using the plugin.

Is there any downside to adding a label to the button?

**Comment by robinpyon** [comment]
I believe this ambiguity has been addressed in the latest version of this plugin

There are now two view modes depending on whether you're either selecting an asset (if the plugin was opened as a result of clicking 'select') or if you're browsing (if the plugin was opened by clicking the Media button in the main navbar)

When selecting, a single click will always select an image and close the plugin. Selected assets in this context are still displayed with a checkmark, but this no longer serves as a button, which understandably was quite confusing!

When browsing, a single click will open the edit asset dialog.
